version: '2'
services:
  tomcat:
   image: "drosenbauer/rpi3-tomcat8-jdk8"

  nginx:
   build:
     context: ./nginx
   image: "test/nginx"
   depends_on:
     - tomcat
   links:
     - tomcat
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  lb:
   build:
     context: ./haproxy
   image: "test/haproxy"
   ports:
     - "80:80"
     - "443:443"
     - "1234:1234"
   depends_on:
    - nginx
   links:
     - nginx
   volumes:
     - ./haproxy/haproxy.cfg:/tmp/conf_override/haproxy.cfg:ro
     - ./certs/pi.jmob.net.pem:/etc/haproxy/certs/pi.jmob.net.pem:ro

